In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [103]:
from sklearn.datasets import load_iris

In [104]:
!pip install tensorflow
from tensorflow.keras.layers import Dense

In [105]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.utils import to_categorical

In [106]:
data = load_iris()
features =data['data']
target = data['target']

In [107]:
targets = to_categorical(target, num_classes=3)
targets

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [108]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, targets)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)

In [109]:
model = Sequential()
model.add(Dense(100,input_shape=(features.shape[1],)))
model.add(Dense(30,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [110]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 100)               500       
                                                                 
 dense_43 (Dense)            (None, 30)                3030      
                                                                 
 dense_44 (Dense)            (None, 20)                620       
                                                                 
 dense_45 (Dense)            (None, 10)                210       
                                                                 
 dense_46 (Dense)            (None, 3)                 33        
                                                                 
Total params: 4,393
Trainable params: 4,393
Non-trainable params: 0
_________________________________________________________________


In [111]:
import tensorflow
 
model.compile(optimizer="sgd",
              loss=tensorflow.keras.losses.CategoricalCrossentropy(),
              metrics=['accuracy'])    

In [112]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))

Epoch 1/10
3/3 [==============================] - 1s 154ms/step - loss: 1.1505 - accuracy: 0.3810 - val_loss: 0.9569 - val_accuracy: 0.6071
Epoch 2/10
3/3 [==============================] - 0s 28ms/step - loss: 0.9593 - accuracy: 0.5000 - val_loss: 0.9435 - val_accuracy: 0.6786
Epoch 3/10
3/3 [==============================] - 0s 27ms/step - loss: 0.9487 - accuracy: 0.5714 - val_loss: 0.9143 - val_accuracy: 0.6786
Epoch 4/10
3/3 [==============================] - 0s 25ms/step - loss: 0.8981 - accuracy: 0.6310 - val_loss: 0.8833 - val_accuracy: 0.6786
Epoch 5/10
3/3 [==============================] - 0s 24ms/step - loss: 0.8582 - accuracy: 0.6071 - val_loss: 0.8457 - val_accuracy: 0.6786
Epoch 6/10
3/3 [==============================] - 0s 25ms/step - loss: 0.8421 - accuracy: 0.6310 - val_loss: 0.8057 - val_accuracy: 0.6429
Epoch 7/10
3/3 [==============================] - 0s 23ms/step - loss: 0.7993 - accuracy: 0.6905 - val_loss: 0.7890 - val_accuracy: 0.5000
Epoch 8/10
3/3 [==========

In [113]:
X_train.shape

(84, 4)

In [114]:
y_train.shape

(84, 3)

In [115]:
y_pred = model.predict(X_test)

In [116]:
y_pred

array([[0.7328088 , 0.10096589, 0.16622533],
       [0.7849859 , 0.07564183, 0.13937226],
       [0.29977703, 0.34434927, 0.35587373],
       [0.22326891, 0.40120792, 0.37552312],
       [0.28058553, 0.35618833, 0.36322618],
       [0.28569216, 0.35183167, 0.36247614],
       [0.77152467, 0.08225892, 0.14621644],
       [0.2692193 , 0.36220914, 0.36857155],
       [0.24025555, 0.38025123, 0.37949324],
       [0.2286561 , 0.40887338, 0.36247048],
       [0.78179646, 0.07590035, 0.14230323],
       [0.22609805, 0.400482  , 0.37341997],
       [0.22510844, 0.40341514, 0.3714764 ],
       [0.7507092 , 0.09116434, 0.15812647],
       [0.7629608 , 0.08515478, 0.15188453],
       [0.21166773, 0.4183351 , 0.36999717],
       [0.23497294, 0.38656074, 0.37846637],
       [0.2294127 , 0.3858951 , 0.3846922 ],
       [0.24491696, 0.37324187, 0.38184112],
       [0.3246155 , 0.33064282, 0.34474167],
       [0.2241554 , 0.392997  , 0.38284767],
       [0.28851703, 0.35459462, 0.3568883 ],
       [0.

# Preprocessing code

In [117]:
model.save("NN.h5")

In [118]:
from tensorflow.keras.models import load_model

In [119]:
model = load_model("./NN.h5")

In [120]:
clas = model.predict([[0.2,0.4,0.5,0.3]])
clas

array([[0.3173424 , 0.34863707, 0.33402056]], dtype=float32)

In [121]:
np.argmax(clas)

1

In [122]:
classes = ['class1', 'class2', 'class3']
classes[np.argmax(clas)]

'class2'